/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE examBaseService PLEASE EDIT ../exam.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exam } from '../../domain/schoolmng_db/exam';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Exam.service.ts
 */

/*
 * SCHEMA DB Exam
 *
	{
		Score: {
			type: 'Number',
			required : true
		},
		place: {
			type: 'String',
			required : true
		},
		valid: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_Course: {
			type: Schema.ObjectId,
			ref : "Exam"
		},
		_Student: {
			type: Schema.ObjectId,
			ref : "Exam"
		},
		_Teacher: {
			type: Schema.ObjectId,
			ref : "Exam"
		},
	}
 *
 */
@Injectable()
export class ExamBaseService {

    contextUrl: string = environment.endpoint + '/exam';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ExamService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Exam): Observable<Exam> {
        return this.http
            .post<Exam>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ExamService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ExamService.findBy_Course
    *   @description CRUD ACTION findBy_Course
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_Course(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_Course/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBy_Student
    *   @description CRUD ACTION findBy_Student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_Student(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_Student/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.findBy_Teacher
    *   @description CRUD ACTION findBy_Teacher
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_Teacher(id: string): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl + '/findBy_Teacher/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ExamService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Exam> {
        return this.http
            .get<Exam>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ExamService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exam[]> {
        return this.http
            .get<Exam[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * ExamService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Exam): Observable<Exam> {
        return this.http
            .post<Exam>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs


    /**
    * ExamService.Validate
    *   @description this is used to validate the exam
    *   @param String id ID of the exam
    *   @returns Boolean
    *
    */
    Validate(...params: any[]): Observable<any> {
        return this.http
            .post<any>(this.contextUrl + '/{id}/Validate', {})
            .pipe(
                map(response => response)
            );
    }

}
